# Generated by Django 4.1.3 on 2023-07-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchlist',
            new_name='reviews',
        ),
    ]
