# Generated by Django 4.2.3 on 2023-07-17 09:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_rename_watchlist_review_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='watchlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='watchlist_app.watchlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
